/**
 * Writes each shipped case's source-and-rights ledger into `docs/source-rights/` as markdown.
 *
 *   npm run audit:ledger              # every known case, both locales
 *   npm run audit:ledger young-interference
 *
 * **Why this is a script and not a route.** Story 3.3 shipped the ledger as a `?ledger=1` surface
 * mounting tables into the document, which made `src/ui/SourceRightsLedger.ts` a fourth module in a
 * directory `project-context.md` §Engine holds to exactly three ("Do not add a fourth"), and a fourth
 * visible element outside `#game-container` where the rule allows three, "each either transient or
 * unseen". The code review moved the projection into `src/domain/sources/ledgerReport.ts` — the location
 * `game-architecture.md` §System Location Mapping designates for source and rights presentation — and
 * left the writing here. Epic 3's criterion is "**when** a reviewer **opens** its ledger" and names no
 * route, so a file satisfies it; two documents already described their tables as read from the authored
 * `ledger` block "rather than transcribed here", which was false of hand-written markdown and is true of
 * generated markdown.
 *
 * **Why Vite loads the modules.** `src/**` imports are extensionless, so Node's native type stripping
 * cannot resolve them, and this project pins its dependencies — `vite` is already one, and its
 * `ssrLoadModule` resolves exactly as the dev server does. No new dependency, no build step, no second
 * copy of the resolution rules.
 *
 * The exit code is the point of the whole thing: **non-zero when any audited case is blocked**, so the
 * report is not merely readable but usable by a release step. The evaluator fails closed; this keeps
 * that property observable from outside the module.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { argv, cwd, exit, stderr, stdout } from 'node:process';
import { createServer } from 'vite';

const OUTPUT_DIR = 'docs/source-rights';
const LOCALES = ['en', 'fr'];

const server = await createServer({
    configFile: false,
    root: cwd(),
    server: { middlewareMode: true },
    appType: 'custom',
    logLevel: 'error'
});

try {
    const { KNOWN_CASE_IDS, CaseDefinitionSchema, AssetManifestSchema } =
        await server.ssrLoadModule('/src/schemas/CaseDefinitionSchema.ts');
    const { getSourceRightsLedgerText, renderLedgerMarkdown } =
        await server.ssrLoadModule('/src/domain/sources/ledgerReport.ts');

    const requested = argv.slice(2);
    // An unknown case ID **fails** rather than defaulting. `resolveCaseId` falls back to Young for the
    // *game* route on the stated reasoning that "a mistyped review link should open the game, not a boot
    // error" — correct there, wrong here: the code review found that on an audit the same fallback hands
    // a reviewer a confident BLOCKED ledger for `young-interference` while they believe they audited the
    // prototype. Silence is the failure mode an audit cannot have.
    const unknown = requested.filter((id) => !KNOWN_CASE_IDS.includes(id));
    if (unknown.length > 0) {
        stderr.write(`Unknown case id(s): ${unknown.join(', ')}\nKnown: ${KNOWN_CASE_IDS.join(', ')}\n`);
        exit(2);
    }
    const caseIds = requested.length > 0 ? requested : [...KNOWN_CASE_IDS];

    await mkdir(OUTPUT_DIR, { recursive: true });
    const blocked = [];

    for (const caseId of caseIds) {
        const read = (fileName) => readFile(`public/cases/${caseId}/${fileName}`, 'utf8');
        // Parsed through the production schemas, not read as loose JSON: a report about content that does
        // not validate is a report about nothing, and the refinements are where the ledger's own rules
        // live. `manifestsMatch`' job is done here too — the two files must agree on every `rights` block,
        // which is exactly the drift a generated report would otherwise paper over.
        const definition = CaseDefinitionSchema.parse(JSON.parse(await read('case.json')));
        const manifest = AssetManifestSchema.parse(JSON.parse(await read('asset-manifest.json')));
        if (JSON.stringify(manifest.entries) !== JSON.stringify(definition.assets.entries)) {
            stderr.write(`${caseId}: case.json and asset-manifest.json disagree — fix the mismatch before auditing.\n`);
            exit(2);
        }

        for (const locale of LOCALES) {
            const content = getSourceRightsLedgerText(definition, locale);
            const notice = `_Generated by \`npm run audit:ledger\` from \`public/cases/${caseId}/case.json\` v${definition.version}. Do not edit by hand._`;
            const path = `${OUTPUT_DIR}/${caseId}-ledger.${locale}.md`;
            await writeFile(path, renderLedgerMarkdown(content, notice), 'utf8');
            stdout.write(`${path} — ${content.decision}, ${content.blockers.length} blocker(s)\n`);
            if (locale === 'en' && content.decision === 'blocked') blocked.push(caseId);
        }
    }

    if (blocked.length > 0) {
        stdout.write(`\nBlocked from release: ${blocked.join(', ')}. See the reports above for the named rows.\n`);
        exit(1);
    }
} finally {
    await server.close();
}
